### PR TITLE
Added a file called test-parser in resources

### PR DESCRIPTION
**Pull request by QassemNa**
Hello @Mosallamy and @rodrigo-brito, I have added a new file called test-parser it can extract the name of the file, namespace and also calls inside a function. However, I haven't added namespace to the JSON yet as I haven't fully understood when it changes it can only add the namespace of the file.
If you want to test the file this you must add the path of the example.py for it to work correctly.

### CODE REVIEW

**Comment by rodrigo-brito** [comment]
Hi @QassemNa, great job.

About the namespace, it is necessary only for the high-level (root) node. For python, it is the File. For the file, the namespace is the package name.

**Comment by Mosallamy** [comment]
Hello @rodrigo-brito, we just wanted to know what are the remaining steps so that the plugin work , could you please explain it to us and we will try to write the code 😁 We have read the RefDiff paper so we know a little how it works, but face a problem when trying to understand why certain parts of the code are written.

**Comment by rodrigo-brito** [comment]
There is some work to do. In this part, you need to discover a good way to execute a Python code inside Java module.
https://github.com/Mosallamy/refdiff-python/blob/main/src/main/java/refdiff/parsers/python/PythonPlugin.java#L30-L57

The main problem is the dependencies, maybe it can be used as a global Python code, and the dependencies will be installed on global pip. But, we have other alternatives like https://www.jython.org/, but i don't have time to test it yet.

After it, do you need to adjust this part to create the nodes in CST Tree, i this step the RefDiff create the relationship with node and its parent. 
https://github.com/Mosallamy/refdiff-python/blob/main/src/main/java/refdiff/parsers/python/PythonPlugin.java#L178-L200

 Unit tests is a good way to validate it

**Comment by Mosallamy** [comment]
Okay thanks, we will start running Python dependencies inside Java

**Comment by Mosallamy** [comment]
Hello @rodrigo-brito, 

- we've successfully ran the parser inside a RefDiff project and the JSON data has been mapped to objects via the ObjectMapper.
- I've checked the node object and it contained all of the nodes from the project
- the root object was returned from the parse method and I think the AST has been converted to CST
 
Also we created a repo containing a file that has been refactored and when running the program it returns that a MOVE refactoring has been detected although there was no MOVE refactoring in the file.
- We added the code to run the python plugin in the src/main/java folder and it contains the url for the repo for the refactoring example

Can you please tell us what should we adjust in this part https://github.com/Mosallamy/refdiff-python/blob/main/src/main/java/refdiff/parsers/python/PythonPlugin.java#L178-L200 so that the tool can detect the refactoring?

Thank you 😃

**Comment by rodrigo-brito** [comment]
Hi @Mosallamy, I will try to check it today. I think we are close to finishing it.

**Comment by Mosallamy** [comment]
Ok thanks! Also I updated the parser file

**Comment by Mosallamy** [comment]
Hello @rodrigo-brito, is there anything that we can do in order to finish the CST conversion? we tried to edit some parts in the plugin that is responsible for converting AST to CST but it did not work unfortianeyl
Thanks 😃

**Comment by QassemNa** [comment]
Hi @rodrigo-brito, I have been able to exctract only the rename method but I can't figure out why it only shows the rename method, do you have any ideas on how to solve it? Thanks!

**Pull request merged**
